import re

def rewrite_pdf_generator():
    path = "c:/Users/uikey/OneDrive/Desktop/locitra/backend/services/reports/reportGenerator.js"
    
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    # The new generatePDF function
    new_func = """exports.generatePDF = (savedLeads, options, res) => {

    const {
        companyName = "Your Agency",
        customMessage = "",
        keyword = "Businesses",
        city = "",
        scanResults = []
    } = options

    const businesses = scanResults.length > 0 ? scanResults : savedLeads

    const doc = new PDFDocument({ margin: 50, size: "A4" })

    res.setHeader("Content-Type", "application/pdf")
    res.setHeader(
        "Content-Disposition",
        `attachment; filename="Locitra-Report-${city || "Market"}.pdf"`
    )

    doc.pipe(res)

    const checkPage = (heightNeeded) => {
        if (doc.y + heightNeeded > 750) doc.addPage()
    }

    const addSectionTitle = (title) => {
        checkPage(80)
        doc.y += 30 // Margin-top 30px
        doc.fill("#0f172a").fontSize(18).font("Helvetica-Bold").text(title, 50, doc.y)
        doc.y += 15 // Margin-bottom 15px
    }

    /* ────────────────────────────────────────────────────────
       1. COVER PAGE
    ──────────────────────────────────────────────────────── */
    doc.rect(0, 0, doc.page.width, 120).fill("#0f172a")
    doc.fill("#fff").fontSize(24).font("Helvetica-Bold")
        .text("Locitra", 50, 35)
    doc.fill("#94a3b8").fontSize(12).font("Helvetica")
        .text("AI-Powered Local Market Intelligence", 50, 65)

    doc.fill("#6366f1").fontSize(12).font("Helvetica-Bold")
        .text(`Prepared by: ${companyName}`, 0, 35, { align: "right", width: doc.page.width - 50 })

    doc.moveDown(8)

    doc.fill("#0f172a").fontSize(28).font("Helvetica-Bold")
        .text(`Market Opportunity Report`, { align: "center" })
    doc.fill("#6366f1").fontSize(16).font("Helvetica")
        .text(`${keyword.charAt(0).toUpperCase() + keyword.slice(1)} in ${city}`, { align: "center" })
    doc.moveDown(1)
    
    doc.fill("#475569").fontSize(12).font("Helvetica")
        .text(`Report Date: ${new Date().toLocaleDateString("en-US", { dateStyle: "long" })}`, { align: "center" })
    doc.moveDown(0.5)
    doc.fill("#94a3b8").fontSize(10).font("Helvetica-Oblique")
        .text(`Generated by Locitra`, { align: "center" })

    if (customMessage) {
        doc.moveDown(4)
        doc.rect(50, doc.y, doc.page.width - 100, 1).fill("#e2e8f0")
        doc.moveDown(1)
        doc.fill("#475569").fontSize(12).font("Helvetica-Oblique").text(customMessage, 50, doc.y, { align: "center", width: doc.page.width - 100 })
    }

    doc.addPage()

    /* ────────────────────────────────────────────────────────
       CALCULATIONS
    ──────────────────────────────────────────────────────── */
    const totalBusinesses = businesses.length
    const avgRating = totalBusinesses ? (businesses.reduce((sum, l) => sum + (l.rating || 0), 0) / totalBusinesses).toFixed(1) : 0
    const avgReviews = totalBusinesses ? Math.round(businesses.reduce((sum, l) => sum + (l.reviews || 0), 0) / totalBusinesses) : 0
    
    const highOpportunity = businesses.filter(b => (b.opportunityScore || 0) >= 70).length
    const noWebsite = businesses.filter(b => !b.website).length
    const lowReviews = businesses.filter(b => (b.reviews || 0) < 30).length
    const lowRating = businesses.filter(b => b.rating && b.rating < 4.0).length
    const weakSeo = businesses.filter(b => b.website && (!b.rating || b.rating < 4.0 || (b.reviews || 0) < 30)).length

    /* ────────────────────────────────────────────────────────
       2. MARKET SIZE (NEW SECTION)
    ──────────────────────────────────────────────────────── */
    addSectionTitle("2. Market Size")
    
    const sizeBaseX = 50
    doc.fontSize(12).font("Helvetica-Bold").fill("#1e293b").text(`Businesses analyzed: `, sizeBaseX, doc.y, { continued: true }).font("Helvetica").fill("#475569").text(totalBusinesses)
    doc.moveDown(0.5)
    doc.font("Helvetica-Bold").fill("#1e293b").text(`High opportunity businesses: `, sizeBaseX, doc.y, { continued: true }).font("Helvetica").fill("#475569").text(highOpportunity)
    doc.moveDown(0.5)
    doc.font("Helvetica-Bold").fill("#1e293b").text(`Saved prospects: `, sizeBaseX, doc.y, { continued: true }).font("Helvetica").fill("#475569").text(savedLeads.length)
    
    doc.addPage()

    /* ────────────────────────────────────────────────────────
       3. EXECUTIVE SUMMARY
    ──────────────────────────────────────────────────────── */
    addSectionTitle("3. Executive Summary")
    doc.fill("#334155").fontSize(11).font("Helvetica")
        .text(`This report analyzes ${totalBusinesses} businesses in the targeted market. We have identified key areas for improvement that present immediate revenue opportunities for marketing services.`)
    doc.moveDown(1)

    const execBaseX = 50
    doc.font("Helvetica-Bold").fill("#1e293b").text(`Total Businesses Analyzed: `, execBaseX, doc.y, { continued: true }).font("Helvetica").fill("#475569").text(totalBusinesses)
    doc.moveDown(0.3)
    doc.font("Helvetica-Bold").fill("#1e293b").text(`Average Rating: `, execBaseX, doc.y, { continued: true }).font("Helvetica").fill("#475569").text(avgRating)
    doc.moveDown(0.3)
    doc.font("Helvetica-Bold").fill("#1e293b").text(`Average Reviews: `, execBaseX, doc.y, { continued: true }).font("Helvetica").fill("#475569").text(avgReviews)
    doc.moveDown(0.3)
    doc.font("Helvetica-Bold").fill("#1e293b").text(`High Opportunity Businesses: `, execBaseX, doc.y, { continued: true }).font("Helvetica").fill("#475569").text(`${highOpportunity} (Score > 70)`)
    doc.moveDown(0.3)
    doc.font("Helvetica-Bold").fill("#1e293b").text(`Businesses Without Website: `, execBaseX, doc.y, { continued: true }).font("Helvetica").fill("#475569").text(noWebsite)
    doc.moveDown(0.3)
    doc.font("Helvetica-Bold").fill("#1e293b").text(`Businesses With Low Reviews: `, execBaseX, doc.y, { continued: true }).font("Helvetica").fill("#475569").text(`${lowReviews} (< 30 reviews)`)

    doc.moveDown(2)

    /* ────────────────────────────────────────────────────────
       4. MARKET OPPORTUNITY BREAKDOWN
    ──────────────────────────────────────────────────────── */
    addSectionTitle("4. Market Opportunity Breakdown")

    doc.fontSize(12).fill("#1e293b").font("Helvetica-Bold").text("Website Opportunities: ", { continued: true }).font("Helvetica").fill("#475569").text(`${noWebsite} businesses without a website`)
    doc.moveDown(0.3)
    doc.font("Helvetica-Bold").fill("#1e293b").text("Review Opportunities: ", { continued: true }).font("Helvetica").fill("#475569").text(`${lowReviews} businesses with review count < 30`)
    doc.moveDown(0.3)
    doc.font("Helvetica-Bold").fill("#1e293b").text("Reputation Opportunities: ", { continued: true }).font("Helvetica").fill("#475569").text(`${lowRating} businesses with rating < 4.0`)
    doc.moveDown(0.3)
    doc.font("Helvetica-Bold").fill("#1e293b").text("SEO Opportunities: ", { continued: true }).font("Helvetica").fill("#475569").text(`${weakSeo} businesses with a website but weak metrics`)

    doc.moveDown(2)

    /* ────────────────────────────────────────────────────────
       5. TOP BUSINESS OPPORTUNITIES
    ──────────────────────────────────────────────────────── */
    addSectionTitle("5. Top Business Opportunities")
    doc.fill("#334155").fontSize(11).font("Helvetica").text("The following businesses have the highest opportunity scores and immediate weaknesses.")
    doc.moveDown(1)

    const topOps = [...businesses].sort((a, b) => (b.opportunityScore || 0) - (a.opportunityScore || 0)).slice(0, 10)

    topOps.forEach(lead => {
        checkPage(140)
        doc.rect(50, doc.y, doc.page.width - 100, 95).fill("#f8fafc").stroke("#e2e8f0")
        doc.moveDown(0.5)
        
        doc.fill("#0f172a").fontSize(13).font("Helvetica-Bold").text(`  ${lead.name || "Unknown Business"}`, 55, doc.y)
        doc.moveDown(0.3)
        doc.fill("#475569").fontSize(10).font("Helvetica")
        doc.text(`  Rating: ${lead.rating || "N/A"}   |   Reviews: ${lead.reviews || 0}   |   Website: ${lead.website ? "Yes" : "No"}   |   Score: ${lead.opportunityScore || 0}`, 55, doc.y)
        doc.moveDown(0.5)
        
        let weaknesses = []
        if (!lead.website) weaknesses.push("No website")
        if ((lead.reviews || 0) < 30) weaknesses.push("Low reviews")
        if (lead.rating && lead.rating < 4.0) weaknesses.push("Low rating")
        if (lead.rating && lead.rating < avgRating) weaknesses.push("Competitors outranking")
        
        doc.fill("#ef4444").font("Helvetica-Bold").text(`  Detected Weaknesses: `, 55, doc.y, { continued: true })
            .font("Helvetica").fill("#334155").text(weaknesses.length > 0 ? weaknesses.join(", ") : "None immediately detected")
        
        doc.y += 12 // margin-bottom 12px for business block
    })

    doc.addPage()

    /* ────────────────────────────────────────────────────────
       6. COMPETITOR COMPARISON
    ──────────────────────────────────────────────────────── */
    addSectionTitle("6. Competitor Comparison")
    doc.fill("#334155").fontSize(11).font("Helvetica").text("Gap analysis between high-performing competitors and weaker businesses, sorted by review count.")
    doc.moveDown(1)

    const compLeads = [...businesses].sort((a, b) => (b.reviews || 0) - (a.reviews || 0)).slice(0, 15)
    
    let x = 50
    const compCols = [250, 100, 100]
    const compHeads = ["Business Name", "Reviews", "Rating"]
    
    doc.fill("#6366f1").fontSize(10).font("Helvetica-Bold")
    compHeads.forEach((h, i) => { doc.text(h, x, doc.y, { width: compCols[i], lineBreak: false }); x += compCols[i] })
    doc.moveDown(0.5)
    doc.rect(50, doc.y, doc.page.width - 100, 1).fill("#e2e8f0")
    doc.moveDown(0.5)

    compLeads.forEach((lead, idx) => {
        checkPage(30)
        x = 50
        const fillCol = idx % 2 === 0 ? "#f8fafc" : "#fff"
        doc.rect(48, doc.y - 4, doc.page.width - 96, 18).fill(fillCol)
        
        doc.fill("#334155").fontSize(9).font("Helvetica")
        doc.text((lead.name || "").slice(0, 40), x, doc.y, { width: compCols[0], lineBreak: false }); x += compCols[0]
        doc.text(String(lead.reviews || 0), x, doc.y, { width: compCols[1], lineBreak: false }); x += compCols[1]
        doc.text(String(lead.rating || "N/A"), x, doc.y, { width: compCols[2], lineBreak: false }); x += compCols[2]
        doc.moveDown(1)
    })

    doc.moveDown(2)

    /* ────────────────────────────────────────────────────────
       7. GOOGLE BUSINESS PROFILE ANALYSIS
    ──────────────────────────────────────────────────────── */
    addSectionTitle("7. Google Business Profile Analysis")
    
    const gmbLeads = [...businesses].sort((a,b) => (b.opportunityScore||0) - (a.opportunityScore||0)).slice(0, 10)
    
    gmbLeads.forEach(lead => {
        checkPage(120)
        doc.fill("#1e293b").fontSize(11).font("Helvetica-Bold").text(lead.name || "Business")
        doc.fill("#475569").fontSize(9).font("Helvetica")
        doc.text(`Rating: ${lead.rating||"N/A"} | Reviews: ${lead.reviews||0} | Website: ${lead.website ? "Yes" : "Missing"}`)
        doc.text(`Address: ${lead.address || "Missing Address"}`)
        doc.text(`Phone: ${lead.phone || "Missing Phone"}`)
        
        let missing = []
        if (!lead.website) missing.push("Website")
        if (!lead.phone) missing.push("Phone Number")
        if (!lead.address) missing.push("Address")
        
        if (missing.length > 0) {
            doc.fill("#ef4444").text(`Missing GBP Info: ${missing.join(", ")}`)
        } else {
            doc.fill("#10b981").text(`GBP Profile looks complete`)
        }
        doc.y += 12 // margin-bottom 12px
    })

    /* ────────────────────────────────────────────────────────
       8. WEBSITE SEO ANALYSIS
    ──────────────────────────────────────────────────────── */
    addSectionTitle("8. Website SEO Analysis")
    doc.fill("#334155").fontSize(10).font("Helvetica").text("Note: Full live SEO audits are performed asynchronously. Snapshot data below.")
    doc.moveDown(1)

    const seoLeads = [...businesses].filter(l => l.website).slice(0, 8)
    if (seoLeads.length === 0) {
        doc.text("No websites found in top leads to analyze.")
    } else {
        seoLeads.forEach(lead => {
            checkPage(80)
            doc.fill("#1e293b").fontSize(11).font("Helvetica-Bold").text(lead.name || "Business")
            doc.fill("#475569").fontSize(9).font("Helvetica").text(`Website: ${lead.website}`)
            doc.fill("#64748b").font("Helvetica-Oblique").text("SEO analysis unavailable")
            doc.y += 12 // margin-bottom 12px
        })
    }

    doc.moveDown(2)

    /* ────────────────────────────────────────────────────────
       9. OPPORTUNITY SCORE EXPLANATION
    ──────────────────────────────────────────────────────── */
    addSectionTitle("9. Opportunity Score Explanation")
    doc.fill("#334155").fontSize(10).font("Helvetica")
        .text("The Locitra Opportunity Score (0-100) is calculated based on several critical factors:")
    doc.moveDown(0.5)
    doc.text("• No Website: High priority signal indicating immediate need for web design.")
    doc.text("• Low Reviews: Indicates a need for reputation management campaigns (<30 reviews = higher score).")
    doc.text("• Low Rating: Indicates a need to counteract negative sentiment (<4.0 rating = higher score).")
    doc.text("• Competitor Gap: Larger gap between this business and market leaders increases the score.")
    
    doc.moveDown(2)

    /* ────────────────────────────────────────────────────────
       10. REVENUE OPPORTUNITY ESTIMATE
    ──────────────────────────────────────────────────────── */
    addSectionTitle("10. Revenue Opportunity Estimate")
    
    const valWeb = 1500
    const valSeo = 750
    const valRev = 500 // user said "Low reviews x $500 per month"

    const estWeb = noWebsite * valWeb
    const estSeo = weakSeo * valSeo
    const estRev = lowReviews * valRev
    const valTotal = estWeb + estSeo + estRev

    doc.fill("#334155").fontSize(11).font("Helvetica")
    doc.text(`Potential Website Projects (${noWebsite}): $${estWeb.toLocaleString()}`)
    doc.text(`Potential SEO Campaigns (${weakSeo}): $${estSeo.toLocaleString()}/mo`)
    doc.text(`Potential Review Campaigns (${lowReviews}): $${estRev.toLocaleString()}/mo`)
    doc.moveDown(0.5)
    doc.fill("#10b981").fontSize(14).font("Helvetica-Bold").text(`Total Estimated Pipeline Value: $${valTotal.toLocaleString()}`)

    doc.moveDown(2)

    /* ────────────────────────────────────────────────────────
       11. AI STRATEGY RECOMMENDATIONS
    ──────────────────────────────────────────────────────── */
    addSectionTitle("11. AI Strategy Recommendations")
    doc.fill("#334155").fontSize(11).font("Helvetica")
        .text(`This market shows strong demand but many businesses have weak review profiles and limited SEO optimization.`)
    doc.moveDown(0.5)
    doc.font("Helvetica-Bold").text("Suggested Services to Pitch:")
    doc.font("Helvetica").text("• Web design & development (Target businesses with missing websites)")
    doc.text("• Reputation Management & Review Campaigns (Target businesses <4.0 rating or <30 reviews)")
    doc.text("• Local SEO Optimization (Target businesses with websites but weak metrics)")

    /* ────────────────────────────────────────────────────────
       12. TOP PROSPECT LIST
    ──────────────────────────────────────────────────────── */
    addSectionTitle("12. Top Prospect List")

    const cols = [210, 70, 170]
    const heads = ["Business Name", "Opportunity Score", "Primary Reason for Opportunity"]
    const xBase = 50

    /* Header row */
    x = xBase
    doc.fill("#6366f1").fontSize(10).font("Helvetica-Bold")
    heads.forEach((h, i) => { doc.text(h, x, doc.y, { width: cols[i], lineBreak: false }); x += cols[i] })
    doc.moveDown(0.5)
    doc.rect(xBase, doc.y, doc.page.width - 100, 1).fill("#e2e8f0")
    doc.moveDown(0.5)

    const finalLeads = [...savedLeads].sort((a, b) => (b.opportunityScore || 0) - (a.opportunityScore || 0)).slice(0, 30)

    finalLeads.forEach((lead, idx) => {
        checkPage(30)
        x = xBase

        const fillColour = idx % 2 === 0 ? "#f8fafc" : "#fff"
        doc.rect(xBase - 2, doc.y - 4, doc.page.width - 96, 20).fill(fillColour)

        let reason = "General Optimization"
        if (!lead.website) reason = "Needs Website"
        else if (lead.rating && lead.rating < 4.0) reason = "Poor Reputation"
        else if ((lead.reviews || 0) < 30) reason = "Low Review Count"

        doc.fill("#334155").fontSize(9).font("Helvetica")
        doc.text((lead.name || "Unknown Business").slice(0, 35), x, doc.y, { width: cols[0], lineBreak: false }); x += cols[0]
        doc.text(String(lead.opportunityScore || 0), x, doc.y, { width: cols[1], lineBreak: false }); x += cols[1]
        doc.text(reason, x, doc.y, { width: cols[2], lineBreak: false }); x += cols[2]

        doc.moveDown(1.5)
    })

    /* ── Footer ──────────────────────────────────── */
    doc.moveDown(2)
    doc.rect(50, doc.y, doc.page.width - 100, 0.5).fill("#e2e8f0")
    doc.moveDown(0.3)
    doc.fill("#94a3b8").fontSize(9)
        .text(`© ${new Date().getFullYear()} ${companyName} — Powered by Locitra`, { align: "center" })

    doc.end()
}"""

    # Replace exports.generatePDF block
    start_str = "exports.generatePDF ="
    end_str = "exports.generateCSV ="
    
    start_idx = content.find(start_str)
    end_idx = content.find(end_str)
    
    if start_idx != -1 and end_idx != -1:
        new_content = content[:start_idx] + new_func + "\n\n/* ── CSV Generator ──────────────────────────────────────────\n   Returns a CSV string.\n────────────────────────────────────────────────────────────── */\n" + content[end_idx:]
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print("Successfully updated reportGenerator.js")
    else:
        print("Could not find the function boundaries.")

if __name__ == "__main__":
    rewrite_pdf_generator()
