/**
 * reportGenerator.js
 * Professional SaaS-style PDF + CSV report exporter.
 * Mimics BrightLocal / Semrush clean layout logic.
 * Uses ONLY live dashboard scanResults.
 */

const PDFDocument = require("pdfkit")
const axios = require("axios")

async function fetchChartBuffer(chartConfig) {
    try {
        const res = await axios.post("https://quickchart.io/chart", {
            chart: chartConfig,
            format: "png",
            width: 600,
            height: 350,
            backgroundColor: "white"
        }, { responseType: "arraybuffer" })
        return res.data
    } catch (e) {
        console.error("Chart generation error:", e.message)
        return null
    }
}

/* ── Helper styles ────────────────────────────────────────── */
const C_DARK = "#0f172a"
const C_MUTED = "#64748b"
const C_LIGHT = "#f1f5f9"
const C_BRAND = "#6366f1"
const C_GREEN = "#10b981"
const C_RED = "#ef4444"

/* ── PDF Generator ────────────────────────────────────────── */
exports.generatePDF = async (savedLeads_DEPRECATED, options, res) => {
    try {
        const {
            companyName = "Your Agency",
            keyword = "Businesses",
            city = "Market",
            scanResults = []
        } = options

        // Strictly enforce using the dashboard scans only
        const businesses = scanResults

        if (!businesses || businesses.length === 0) {
            throw new Error("No scan results available.")
        }

        const doc = new PDFDocument({ margin: 50, size: "A4" })

        res.setHeader("Content-Type", "application/pdf")
        res.setHeader(
            "Content-Disposition",
            `attachment; filename="Locitra-Report-${city || "Market"}.pdf"`
        )

        doc.pipe(res)

        const checkPage = (heightNeeded) => {
            if (doc.y + heightNeeded > 750) doc.addPage()
        }

        const addSectionTitle = (title) => {
            checkPage(100)
            doc.moveDown(2)
            doc.y += 40 // Margin top 40px
            doc.fill(C_DARK).fontSize(18).font("Helvetica-Bold").text(title, 50, doc.y)
            doc.y += 20 // Margin bottom 20px
            doc.rect(50, doc.y - 10, doc.page.width - 100, 1.5).fill(C_LIGHT)
            doc.moveDown(1)
        }

        /* ────────────────────────────────────────────────────────
           1. COVER PAGE
        ──────────────────────────────────────────────────────── */
        // Branding Header Band
        doc.rect(0, 0, doc.page.width, 140).fill(C_DARK)
        doc.fill("#ffffff").fontSize(26).font("Helvetica-Bold").text("Locitra", 50, 45)
        doc.fill(C_BRAND).fontSize(13).font("Helvetica-Bold").text(`Prepared For: ${companyName}`, 0, 45, { align: "right", width: doc.page.width - 50 })
        doc.fill("#94a3b8").fontSize(12).font("Helvetica").text("Targeted Market Intelligence", 50, 75)

        doc.moveDown(8)
        
        // Main Title
        doc.fill(C_DARK).fontSize(28).font("Helvetica-Bold")
            .text(`Locitra Market Intelligence Report`, { align: "center" })
        
        doc.moveDown(1.5)
        doc.fill(C_MUTED).fontSize(14).font("Helvetica")
            .text(`Market Keyword: ${keyword.charAt(0).toUpperCase() + keyword.slice(1)}`, { align: "center" })
        doc.moveDown(0.3)
        doc.text(`City: ${city}`, { align: "center" })
        doc.moveDown(0.3)
        doc.text(`Report Date: ${new Date().toLocaleDateString("en-US", { dateStyle: "long" })}`, { align: "center" })

        doc.moveDown(2)
        doc.fill("#94a3b8").fontSize(12).font("Helvetica-Oblique")
            .text(`Generated by Locitra`, { align: "center" })

        doc.addPage()

        /* ────────────────────────────────────────────────────────
           CALCULATIONS
        ──────────────────────────────────────────────────────── */
        const totalBusinesses = businesses.length
        
        const highOppCount = businesses.filter(b => (b.opportunityScore || 0) >= 70).length
        const medOppCount = businesses.filter(b => (b.opportunityScore || 0) >= 40 && (b.opportunityScore || 0) < 70).length
        const lowOppCount = businesses.filter(b => (b.opportunityScore || 0) < 40).length
        
        const noWebsite = businesses.filter(b => !b.website).length
        const withWebsite = totalBusinesses - noWebsite

        const lowReviews = businesses.filter(b => (b.reviews || 0) < 30).length
        const lowRating = businesses.filter(b => b.rating && b.rating < 4.0).length
        const avgReviewsBusinesses = businesses.filter(b => (b.reviews || 0) >= 30 && (b.reviews || 0) < 100).length

        let difficulty = "Medium"
        if (totalBusinesses > 0) {
            const highOppPct = highOppCount / totalBusinesses
            if (highOppPct < 0.2) difficulty = "High"
            else if (highOppPct > 0.5) difficulty = "Low"
        }

        const estRev = (noWebsite * 1500) + (lowReviews * 500)

        /* ────────────────────────────────────────────────────────
           2. MARKET OVERVIEW
        ──────────────────────────────────────────────────────── */
        addSectionTitle("Market Overview")
        
        const bx1 = 50, bx2 = 300
        let currentY = doc.y

        // Left Column
        doc.fontSize(12).font("Helvetica-Bold").fill(C_DARK).text(`Total Businesses Scanned: `, bx1, currentY, { continued: true }).font("Helvetica").fill(C_MUTED).text(totalBusinesses)
        doc.moveDown(0.8)
        doc.font("Helvetica-Bold").fill(C_DARK).text(`Websites Identified: `, bx1, doc.y, { continued: true }).font("Helvetica").fill(C_MUTED).text(withWebsite)
        doc.moveDown(0.8)
        doc.font("Helvetica-Bold").fill(C_DARK).text(`High Opportunity Leads: `, bx1, doc.y, { continued: true }).font("Helvetica").fill(C_MUTED).text(highOppCount)
        
        // Right Column
        doc.font("Helvetica-Bold").fill(C_DARK).text(`Market Difficulty: `, bx2, currentY, { continued: true }).font("Helvetica").fill(C_MUTED).text(difficulty)
        doc.moveDown(0.8)
        doc.font("Helvetica-Bold").fill(C_DARK).text(`Estimated Revenue Opportunity: `, bx2, currentY + 23, { continued: true }).font("Helvetica").fill(C_GREEN).text(`$${estRev.toLocaleString()}`)

        doc.y = currentY + 70

        /* ────────────────────────────────────────────────────────
           3. MARKET WEAKNESS INSIGHTS
        ──────────────────────────────────────────────────────── */
        addSectionTitle("Market Weakness Insights")

        currentY = doc.y
        doc.fontSize(12).font("Helvetica-Bold").fill(C_DARK).text(`Businesses Without Website: `, bx1, currentY, { continued: true }).font("Helvetica").fill(C_MUTED).text(noWebsite)
        doc.moveDown(0.8)
        doc.font("Helvetica-Bold").fill(C_DARK).text(`Businesses With Low Reviews (<30): `, bx1, doc.y, { continued: true }).font("Helvetica").fill(C_MUTED).text(lowReviews)
        doc.moveDown(0.8)
        doc.font("Helvetica-Bold").fill(C_DARK).text(`Businesses With Low Rating (<4.0): `, bx1, doc.y, { continued: true }).font("Helvetica").fill(C_MUTED).text(lowRating)

        doc.font("Helvetica-Bold").fill(C_DARK).text(`Average Review Businesses: `, bx2, currentY, { continued: true }).font("Helvetica").fill(C_MUTED).text(avgReviewsBusinesses)
        doc.moveDown(0.8)
        doc.font("Helvetica-Bold").fill(C_DARK).text(`Total Leads Identified: `, bx2, currentY + 23, { continued: true }).font("Helvetica").fill(C_MUTED).text(totalBusinesses)

        doc.addPage()

        /* ────────────────────────────────────────────────────────
           4. OPPORTUNITY DISTRIBUTION
        ──────────────────────────────────────────────────────── */
        addSectionTitle("Opportunity Distribution")

        const oppChartConfig = {
            type: 'doughnut',
            data: {
                labels: ['High Opportunity', 'Medium Opportunity', 'Low Opportunity'],
                datasets: [{ data: [highOppCount, medOppCount, lowOppCount], backgroundColor: ['#10b981', '#f59e0b', '#ef4444'] }]
            },
            options: { plugins: { title: { display: false } }, legend: { position: 'bottom' } }
        }

        const oppImage = await fetchChartBuffer(oppChartConfig)
        if (oppImage) {
            checkPage(300)
            doc.image(oppImage, doc.page.width/2 - 250, doc.y, { width: 500 })
            doc.y += 320
        }

        /* ────────────────────────────────────────────────────────
           5. COMPETITION DENSITY
        ──────────────────────────────────────────────────────── */
        addSectionTitle("Competition Density")

        // Competition density defined in instructions: X-axis: Business Name, Y-axis: Review Count
        // (Visualizing top 5 and bottom 5 by review count for the chart clarity)
        const densityLeads = [...businesses].sort((a, b) => (b.reviews || 0) - (a.reviews || 0)).slice(0, 10)

        const densityChartConfig = {
            type: 'bar',
            data: {
                labels: densityLeads.map(l => (l.name || "Unknown").slice(0, 15)),
                datasets: [{
                    label: 'Review Count',
                    data: densityLeads.map(l => l.reviews || 0),
                    backgroundColor: '#6366f1'
                }]
            },
            options: { plugins: { title: { display: false } }, legend: { display: false }, scales: { y: { beginAtZero: true } } }
        }

        const densityImage = await fetchChartBuffer(densityChartConfig)
        if (densityImage) {
            checkPage(300)
            doc.image(densityImage, doc.page.width/2 - 250, doc.y, { width: 500 })
            doc.y += 320
        }

        doc.addPage()

        /* ────────────────────────────────────────────────────────
           6. TOP OPPORTUNITIES
        ──────────────────────────────────────────────────────── */
        addSectionTitle("Top Opportunities")

        const cols = [160, 45, 55, 60, 50, 120]
        const heads = ["Business Name", "Rating", "Reviews", "Website", "Score", "Main Weakness"]
        let xBase = 50

        /* Header row */
        let x = xBase
        doc.fill(C_BRAND).fontSize(10).font("Helvetica-Bold")
        heads.forEach((h, i) => { doc.text(h, x, doc.y, { width: cols[i], lineBreak: false }); x += cols[i] })
        doc.moveDown(0.5)
        doc.rect(xBase, doc.y, doc.page.width - 100, 1).fill(C_LIGHT)
        doc.moveDown(0.5)

        const topLeads = [...businesses].sort((a, b) => (b.opportunityScore || 0) - (a.opportunityScore || 0)).slice(0, 10)

        topLeads.forEach((lead, idx) => {
            checkPage(30)
            x = xBase

            const fillColour = idx % 2 === 0 ? "#f8fafc" : "#ffffff"
            doc.rect(xBase - 2, doc.y - 4, doc.page.width - 96, 20).fill(fillColour)

            let reason = "General Optimization"
            if (!lead.website) reason = "No Website"
            else if (lead.rating && lead.rating < 4.0) reason = "Low Rating"
            else if ((lead.reviews || 0) < 30) reason = "Low Reviews"

            doc.fill(C_DARK).fontSize(9).font("Helvetica")
            doc.text((lead.name || "Unknown").slice(0, 30), x, doc.y, { width: cols[0], lineBreak: false }); x += cols[0]
            doc.text(String(lead.rating || "N/A"), x, doc.y, { width: cols[1], lineBreak: false }); x += cols[1]
            doc.text(String(lead.reviews || 0), x, doc.y, { width: cols[2], lineBreak: false }); x += cols[2]
            
            doc.fill(lead.website ? C_MUTED : C_RED)
            doc.text(lead.website ? "Yes" : "Missing", x, doc.y, { width: cols[3], lineBreak: false }); x += cols[3]
            
            doc.fill(C_DARK)
            doc.text(String(lead.opportunityScore || 0), x, doc.y, { width: cols[4], lineBreak: false }); x += cols[4]
            doc.text(reason, x, doc.y, { width: cols[5], lineBreak: false }); x += cols[5]

            doc.moveDown(1.5)
        })

        /* ── Footer ──────────────────────────────────── */
        doc.moveDown(4)
        doc.rect(50, doc.y, doc.page.width - 100, 0.5).fill(C_LIGHT)
        doc.moveDown(0.5)
        doc.fill("#94a3b8").fontSize(10)
            .text(`© ${new Date().getFullYear()} ${companyName} — Powered by Locitra`, { align: "center" })

        doc.end()
    } catch (err) {
        console.error("PDF generation failed:", err)
        if (!res.headersSent) {
            res.status(500).send("Report generation failed")
        }
    }
}

/* ── CSV Generator ────────────────────────────────────────── */
exports.generateCSV = (scanResults) => {

    const columns = [
        "Business Name", "Rating", "Reviews", "Website", "Phone", "Address", "Opportunity Score", "Weakness"
    ]
    
    const getWeakness = (l) => {
        if (!l.website) return "No Website"
        if (l.rating && l.rating < 4.0) return "Low Rating"
        if ((l.reviews || 0) < 30) return "Low Reviews"
        return "General Optimization"
    }

    const mapLeadData = (l) => {
        return [
            l.name || "",
            l.rating || "",
            l.reviews || "",
            l.website || "",
            l.phone || "",
            l.address || "",
            l.opportunityScore || 0,
            getWeakness(l)
        ]
    }

    const esc = (v) => {
        if (v == null) return ""
        const s = String(v)
        return s.includes(",") || s.includes('"') || s.includes("\n")
            ? `"${s.replace(/"/g, '""')}"`
            : s
    }

    const header = columns.join(",")
    const rows = (scanResults || []).map(b => mapLeadData(b).map(val => esc(val)).join(","))

    return [header, ...rows].join("\n")
}
